### PR TITLE
Feature/vite migration

### LINKED ISSUE #18: Update to building with Vite framework
@Greg-Hawkridge mentioned - tell us more...

Reduce compose build times?

### LINKED ISSUE #21: npn depreciation warnings and network failure
Sometimes LocationTracking doesn't build for me. This looks like internet was lost momentarily at an inopportune time. I entered the command over the web, viewed the following printout over the web and then pinged google, all of which otherwise was fine. 
<details><summary>Logs</summary>

```
pi@GrovePi:~/LocationTracking $ dbuild
WARN[0000] /home/pi/LocationTracking/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Building 281.9s (33/46)                                                                                                                                                                                                                                                                                               docker:default
 => [user-input-dc internal] load build definition from Dockerfile                                                                                                                                                                                                                                                                  0.3s
 => => transferring dockerfile: 336B                                                                                                                                                                                                                                                                                                0.0s
 => [dashboard internal] load build definition from Dockerfile                                                                                                                                                                                                                                                                      0.4s
 => => transferring dockerfile: 336B                                                                                                                                                                                                                                                                                                0.0s
 => [identity-sds internal] load build definition from Dockerfile                                                                                                                                                                                                                                                                   0.3s
 => => transferring dockerfile: 228B                                                                                                                                                                                                                                                                                                0.0s
 => [locations-sds internal] load build definition from Dockerfile                                                                                                                                                                                                                                                                  0.4s
 => => transferring dockerfile: 228B                                                                                                                                                                                                                                                                                                0.0s
 => [user-input-dc internal] load metadata for docker.io/library/nginx:latest                                                                                                                                                                                                                                                       1.0s
 => [user-input-dc internal] load metadata for docker.io/library/node:19-alpine                                                                                                                                                                                                                                                     1.0s
 => [locations-sds internal] load metadata for docker.io/digitalshoestring/shoestring-django-rest:v0.0.1                                                                                                                                                                                                                            1.7s
 => [user-input-dc internal] load .dockerignore                                                                                                                                                                                                                                                                                     0.2s
 => => transferring context: 2B                                                                                                                                                                                                                                                                                                     0.0s
 => [dashboard internal] load .dockerignore                                                                                                                                                                                                                                                                                         0.2s
 => => transferring context: 2B                                                                                                                                                                                                                                                                                                     0.0s
 => CACHED [dashboard appbuild 1/6] FROM docker.io/library/node:19-alpine@sha256:8ec543d4795e2e85af924a24f8acb039792ae9fe8a42ad5b4bf4c277ab34b62e                                                                                                                                                                                   0.0s
 => [user-input-dc internal] load build context                                                                                                                                                                                                                                                                                     0.2s
 => => transferring context: 57.58kB                                                                                                                                                                                                                                                                                                0.0s
 => [dashboard stage-1 1/4] FROM docker.io/library/nginx:latest@sha256:fb197595ebe76b9c0c14ab68159fd3c08bd067ec62300583543f0ebda353b5be                                                                                                                                                                                             0.0s
 => [dashboard internal] load build context                                                                                                                                                                                                                                                                                         0.2s
 => => transferring context: 179.90kB                                                                                                                                                                                                                                                                                               0.0s
 => [user-input-dc appbuild 2/6] COPY ./code/package.json /                                                                                                                                                                                                                                                                         0.5s
 => [dashboard appbuild 2/6] COPY ./code/package.json /                                                                                                                                                                                                                                                                             0.5s
 => [locations-sds internal] load .dockerignore                                                                                                                                                                                                                                                                                     0.6s
 => => transferring context: 2B                                                                                                                                                                                                                                                                                                     0.0s
 => [identity-sds internal] load .dockerignore                                                                                                                                                                                                                                                                                      0.5s
 => => transferring context: 2B                                                                                                                                                                                                                                                                                                     0.0s
 => [dashboard appbuild 3/6] RUN npm install                                                                                                                                                                                                                                                                                      279.5s
 => => # npm WARN deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.                                                                  
 => => # npm WARN deprecated @babel/plugin-proposal-numeric-separator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.                                                                                      
 => => # npm WARN deprecated @babel/plugin-proposal-private-methods@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-private-methods instead.                                                                                          
 => => # npm WARN deprecated @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.                                                                                      
 => => # npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.                                                                                                                                                                                                                                   
 => => # npm WARN deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.                                                                                                                                                                                       
 => ERROR [user-input-dc appbuild 3/6] RUN npm install                                                                                                                                                                                                                                                                            275.3s
 => [identity-sds 1/5] FROM docker.io/digitalshoestring/shoestring-django-rest:v0.0.1@sha256:c683aadb7527ecb185427f0e73e0e86d66b2c00496f17da2d527e3d5429e4020                                                                                                                                                                       5.5s
 => => resolve docker.io/digitalshoestring/shoestring-django-rest:v0.0.1@sha256:c683aadb7527ecb185427f0e73e0e86d66b2c00496f17da2d527e3d5429e4020                                                                                                                                                                                    0.2s
 => => sha256:d39174d49bea9f4bc26fbbbb41ed5bde790409491f7fc7065a346d31c944e5be 3.47kB / 3.47kB                                                                                                                                                                                                                                      0.0s
 => => sha256:50833f4960f35025636364de9f307c02c6bc681845fdb1d54972c7fd462f0003 9.03kB / 9.03kB                                                                                                                                                                                                                                      0.0s
 => => sha256:c683aadb7527ecb185427f0e73e0e86d66b2c00496f17da2d527e3d5429e4020 1.08kB / 1.08kB                                                                                                                                                                                                                                      0.0s
 => => sha256:1c72ac905c755734bd43204cbda0df84d7d0cc5a82e4aa39ea32dc3e606d0e5f 167B / 167B                                                                                                                                                                                                                                          0.8s
 => => sha256:094690d8ee1e6f56cca552c71cd418bece82559b70a274be5981f0a4965038d6 2.46MB / 2.46MB                                                                                                                                                                                                                                      2.8s
 => => sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1 32B / 32B                                                                                                                                                                                                                                            0.6s
 => => extracting sha256:1c72ac905c755734bd43204cbda0df84d7d0cc5a82e4aa39ea32dc3e606d0e5f                                                                                                                                                                                                                                           0.0s
 => => extracting sha256:094690d8ee1e6f56cca552c71cd418bece82559b70a274be5981f0a4965038d6                                                                                                                                                                                                                                           0.5s
 => => extracting sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1                                                                                                                                                                                                                                           0.0s
 => [identity-sds internal] load build context                                                                                                                                                                                                                                                                                      0.6s
 => => transferring context: 36.30kB                                                                                                                                                                                                                                                                                                0.1s
 => [locations-sds internal] load build context                                                                                                                                                                                                                                                                                     0.5s
 => => transferring context: 37.50kB                                                                                                                                                                                                                                                                                                0.1s
 => [locations-sds 2/5] COPY ./requirements.txt /requirements.txt                                                                                                                                                                                                                                                                   1.4s
 => [identity-sds 2/5] COPY ./requirements.txt /requirements.txt                                                                                                                                                                                                                                                                    1.4s 
 => [identity-sds 3/5] RUN pip install -r /requirements.txt && rm -f /requirements.txt                                                                                                                                                                                                                                             22.8s 
 => [locations-sds 3/5] RUN pip install -r /requirements.txt && rm -f /requirements.txt                                                                                                                                                                                                                                            21.5s 
 => [locations-sds 4/5] WORKDIR /app                                                                                                                                                                                                                                                                                                1.2s 
 => [locations-sds 5/5] ADD ./code /app/                                                                                                                                                                                                                                                                                            0.7s 
 => [identity-sds 4/5] WORKDIR /app                                                                                                                                                                                                                                                                                                 0.8s 
 => [locations-sds] exporting to image                                                                                                                                                                                                                                                                                              0.7s 
 => => exporting layers                                                                                                                                                                                                                                                                                                             0.5s 
 => => writing image sha256:cf4d5cbb629c4ad08acbbe32cdf472fe6ab4c8e134d99f90fed7eb2d7000d560                                                                                                                                                                                                                                        0.0s 
 => => naming to docker.io/library/locationtracking-locations-sds                                                                                                                                                                                                                                                                   0.0s
 => [identity-sds 5/5] ADD ./code /app/                                                                                                                                                                                                                                                                                             0.4s
 => [identity-sds] exporting to image                                                                                                                                                                                                                                                                                               0.6s
 => => exporting layers                                                                                                                                                                                                                                                                                                             0.5s
 => => writing image sha256:c6a93ecdabf6bb51ebb6ac04886d3eaa4bb54e57bd9f14aa5e15d776049b20d4                                                                                                                                                                                                                                        0.0s
 => => naming to docker.io/library/locationtracking-identity-sds                                                                                                                                                                                                                                                                    0.0s
 => [locations-sds] resolving provenance for metadata file                                                                                                                                                                                                                                                                          0.0s
 => [identity-sds] resolving provenance for metadata file                                                                                                                                                                                                                                                                           0.0s
------                                                                                                                                                                                                                                                                                                                                   
 > [user-input-dc appbuild 3/6] RUN npm install:                                                                                                                                                                                                                                                                                         
186.7 npm WARN deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser                                                                                                                                                                                     
186.7 npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead                                                                                                                                                                                                                                          
187.4 npm WARN deprecated workbox-cacheable-response@6.6.0: workbox-background-sync@6.6.0                                                                                                                                                                                                                                                
187.4 npm WARN deprecated workbox-google-analytics@6.6.0: It is not compatible with newer versions of GA starting with v4, as long as you are using GAv3 it should be ok, but the package is not longer being maintained                                                                                                                 
218.6 npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
221.3 npm WARN deprecated q@1.5.1: You or someone you depend on is using Q, the JavaScript Promise library that gave JavaScript developers strong feelings about promises. They can almost certainly migrate to the native JavaScript promise now. Thank you literally everyone for joining me in this bet against the odds. Be excellent to each other.
221.3 npm WARN deprecated 
221.3 npm WARN deprecated (For a CapTP with native promises, see @endo/eventual-send and @endo/captp)
238.1 npm WARN deprecated abab@2.0.6: Use your platform's native atob() and btoa() methods instead
238.3 npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
238.3 npm WARN deprecated domexception@2.0.1: Use your platform's native DOMException instead
239.7 npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
245.8 npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
260.3 npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
261.4 npm notice 
261.5 npm notice New major version of npm available! 9.6.3 -> 10.9.2
261.5 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.9.2>
261.5 npm notice Run `npm install -g npm@10.9.2` to update!
261.5 npm notice 
261.5 npm ERR! code ETIMEDOUT
261.5 npm ERR! syscall read
261.5 npm ERR! errno -110
261.5 npm ERR! network read ETIMEDOUT
261.5 npm ERR! network This is a problem related to network connectivity.
261.8 npm ERR! network In most cases you are behind a proxy or have bad network settings.
261.8 npm ERR! network 
261.8 npm ERR! network If you are behind a proxy, please make sure that the
261.8 npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
261.8 
261.8 npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-12-12T15_25_14_202Z-debug-0.log
------
failed to solve: process "/bin/sh -c npm install" did not complete successfully: exit code: 146
pi@GrovePi:~/LocationTracking $ ping google.com
PING google.com (142.250.187.206) 56(84) bytes of data.
64 bytes from lhr25s33-in-f14.1e100.net (142.250.187.206): icmp_seq=1 ttl=53 time=5.72 ms
64 bytes from lhr25s33-in-f14.1e100.net (142.250.187.206): icmp_seq=2 ttl=53 time=8.91 ms
^C
--- google.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1002ms
rtt min/avg/max/mdev = 5.718/7.311/8.905/1.593 ms
```

</details>

The next attempt at the build worked (eventually, 500s). 
But will we version bump our way out of depreciated dependencies?
```
 => [user-input-dc appbuild 6/6] RUN npm run build                                                                                                                                                                                                                                                                                101.5s 
 => => # babel-preset-react-app is part of the create-react-app project, which                                                                                                                                                                                                                                                           
 => => # is not maintianed anymore. It is thus unlikely that this bug will                                                                                                                                                                                                                                                               
 => => # ever be fixed. Add "@babel/plugin-proposal-private-property-in-object" to                                                                                                                                                                                                                                                       
 => => # your devDependencies to work around this error. This will make this message                                                                                                                                                                                                                                                     
 => => # go away.                                                                                                                                                                                                                                                                                                                        
 => [dashboard appbuild 6/6] RUN npm run build                                                                                                                                                                                                                                                                                    101.4s 
 => => # babel-preset-react-app is part of the create-react-app project, which                                                                                                                                                                                                                                                           
 => => # is not maintianed anymore. It is thus unlikely that this bug will                                                                                                                                                                                                                                                              
 => => # ever be fixed. Add "@babel/plugin-proposal-private-property-in-object" to                                                                                                                                                                                                                                                      
 => => # your devDependencies to work around this error. This will make this message                                                                                                                                                                                                                                                    
 => => # go away. 
```

### PR DESCRIPTION
**Pull request by Greg-Hawkridge**
* Fixes #18 
* Fixes #21

### CODE REVIEW

**Comment by tobyaharris** [comment]
The git history for this is messy. The base this was committed over was not `main`, nor the head of the open release branch. It's halfway in between the two. 
Can this be rebased onto `release/1.2.0`?

**Comment by tobyaharris** [comment]
Any chance of documentation of how to use the `dev` services in the ymls / alternative dockerfile?

**Comment by Greg-Hawkridge** [comment]
> Any chance of documentation of how to use the `dev` services in the ymls / alternative dockerfile?

set `service` to `dev` in compose file for live updates during development, change back to `app` for deployment

(important to note - live updates can be a little hit and miss at times)

**Comment by tobyaharris** [comment]
In some testing on a pi5 8gb, before this commit (i.e. 79f3a1a5907692d1268af5046ec1a2234ffd31d6) docker compose build reported build time as 206.0s. Now this (7cbbc3893b503f9e5ce5655e6b57add67125452d) builds in 90.4s.

Still a ton of npm depreciation warnings. Including the CJS build of Vite's node API.

**Comment by tobyaharris** [comment]
Testing use, I get this error popup in the bottom right when submitting the update location form. 

Set up a custom location, pre-defined a product and a barcode identifier for it, scan into my location and submission is rejected:

image
Location appears in dashboard but no entries in dash nor state/event records 

Need to re-test before this commit...

**Comment by tobyaharris** [comment]
Restested 79f3a1a5907692d1268af5046ec1a2234ffd31d6 and it works as expected.

**Review by tobyaharris — CHANGES_REQUESTED** [review]
Clean build of this does not allow items to be scanned between locations.

**Comment by tobyaharris** [comment]
dev mode: dayjs is not a function

**Comment by tobyaharris** [comment]
Building this still produces a lot of `npm WARN EBADENGINE Unsupported Engine`, version 19.9.0 of node doesn't appear compatible with vite 5.4.19...
The usual `inflight 1.0.6: This module is not supported, and leaks memory. Do not use it`, using glob 7.2.3 but versions prior to v9 are no longer supported, the two `humanwhocodes` repos (`object-schema` and `config-array`) are depreciated and redirect to `eslint`, but most of all I'm concerned about `The CJS build of Vite's node API is depreciated.`

**Comment by Greg-Hawkridge** [comment]
Bump node to v22

**Review by tobyaharris — APPROVED** [review]
Tested & all featuers working
